[[https://ci.appveyor.com/project/pouar/yadfa/branch/master][file:https://img.shields.io/appveyor/ci/pouar/yadfa/master.svg?style=plastic&logo=appveyor&label=appveyor]]
[[https://gitlab.com/pouar/yadfa/pipelines][file:https://img.shields.io/gitlab/pipeline/pouar/yadfa/master.svg?logo=gitlab&style=plastic&label=gitlab]]

A diaperfur/babyfur themed text adventure/rpg game I'm working on, you play it by typing in Lisp functions, similar to those text adventure games you play by typing in commands, but in Lisp form

Right now, most of the core of the game is done, but is missing a lot of content, and I might need help thinking up content for the game.

So far this has only been tested on Linux and Windows 10, but should be portable enough. I got it to successfully run in SBCL, CCL, and ECL, but I couldn't generate a working image in ECL yet.

* Install Instructions

** for Linux users


I've added a flatpak repo for Linux users, you can add it with

#+BEGIN_SRC shell
flatpak remote-add --if-not-exists yadfa https://gitlab.com/pouar/yadfa/raw/master/flatpak/yadfa.flatpakrepo
#+END_SRC

then install the game with

#+BEGIN_SRC shell
flatpak install yadfa net.pouar.yadfa
#+END_SRC

you can update the game with (it will also be updated when you run ~flatpak update~ which updates all packages installed with flatpak)

#+BEGIN_SRC shell
flatpak update net.pouar.yadfa
#+END_SRC

you can uninstall the game with 

#+BEGIN_SRC shell
flatpak uninstall net.pouar.yadfa
#+END_SRC

** for Windows users

I've also added a chocolatey repo for Windows users. You can add the repo from PowerShell with

#+BEGIN_SRC shell
choco source add -n yadfa -s https://api.bintray.com/nuget/pouar/yadfa-chocolatey
#+END_SRC

then install the game with

#+BEGIN_SRC shell
choco install yadfa
#+END_SRC

you can upgrade the game with (it will also be upgraded when you run ~choco upgrade all~ which upgrades all applications installed with chocolatey)

#+BEGIN_SRC shell
choco upgrade yadfa
#+END_SRC
or uninstall it with

#+BEGIN_SRC shell
choco uninstall yadfa
#+END_SRC

if you no longer need the X Server after uninstalling

#+BEGIN_SRC shell
choco uninstall vcxsrv
#+END_SRC

I use Declt to generate the autogenerated docs, which only works in SBCL, which seems to crash in Windows. Until I can get this working again, you can download the docs here which is generated by the Linux builds

[[https://pouar.gitlab.io/yadfa/yadfa-docs.tar.xz]]
* Mirrors

[[https://cgit.pouar.net/yadfa.git][My Site: https://cgit.pouar.net/yadfa.git]]

[[https://github.com/pouar/yadfa][GitHub: https://github.com/pouar/yadfa]]

[[https://gitlab.com/pouar/yadfa][GitLab: https://gitlab.com/pouar/yadfa]]

[[https://gitgud.io/pouar/yadfa][GitGud: https://gitgud.io/pouar/yadfa]]
