;;;; -*- mode: Common-Lisp; sly-buffer-package: "yadfa"; coding: utf-8-unix; -*-
(in-package :yadfa)
(unless *game* (setf *game* (make-instance 'game)))
(defyadfahook read-frame-command-hooks '()
  "Hooks that run after @code{READ-FRAME-COMMAND} is called in @code{DEFAULT-FRAME-TOP-LEVEL} for @code{CLIM-LISTENER::LISTENER}")
(defyadfahook execute-frame-command-hooks '()
  "Hooks that run after @code{EXECUTE-FRAME-COMMAND} is called in @code{DEFAULT-FRAME-TOP-LEVEL} for @code{CLIM-LISTENER::LISTENER}")
(defyadfahook redisplay-frame-panes-hooks '()
  "Hooks that run after @code{REDISPLAY-FRAME-PANES} is called in @code{DEFAULT-FRAME-TOP-LEVEL} for @code{CLIM-LISTENER::LISTENER}")
(defyadfahook cheat-hooks '()
  "Put functions that sets crap to fixed values here. Intended to be used similar to the feature in Cheat Engine used to set variables to a constant value, although will probably run less frequently and is generally easier to use since it doesn't involve working with memory addresses")
(defyadfahook move-hooks '()
  "Hooks that run each time the player moves to another zone")
(defyadfahook process-potty-hooks '()
  "Hooks that run each time @code{YADFA::PROCESS-POTTY} is run. Called with @var{USER} a cons containing the return values of @code{YADFA:WET} and @code{YADFA:MESS} as arguments")
